
curl 'http://127.0.0.1:3000/sign' 
-H 'Content-Type: application/json;charset=UTF-8' 
--data-binary '{"username":"op1","password":"op1","role":["operation"]}' 

###
http://localhost:3000/auth
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOjU3MTIwODg5MzY3NDI5MTJ9.zq9a4uy732We7lClYCGSrAxDIRqnzY4j2SvW-RqF4gk

###
http://localhost:3000/users/5710239819104256
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOjU3MTAyMzk4MTkxMDQyNTZ9.dIGLa-Fqf7KvupemyRU9cngm5Vnnp_wbSc64PlPJceY

###
http://localhost:3000/modules
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOjU3MTAyMzk4MTkxMDQyNTZ9.dIGLa-Fqf7KvupemyRU9cngm5Vnnp_wbSc64PlPJceY

###
GET http://localhost:3000/modules/5674053578784768
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOjU3MTAyMzk4MTkxMDQyNTZ9.dIGLa-Fqf7KvupemyRU9cngm5Vnnp_wbSc64PlPJceY

###
GET http://127.0.0.1:3000/users
?where={"role":"tutor"}
&sort=_deleted,-_updated
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOjU3MTIwODg5MzY3NDI5MTJ9.zq9a4uy732We7lClYCGSrAxDIRqnzY4j2SvW-RqF4gk

###
curl 'http://127.0.0.1:3000/classes' 
-H 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOjU3MTIwODg5MzY3NDI5MTJ9.zq9a4uy732We7lClYCGSrAxDIRqnzY4j2SvW-RqF4gk' 
-H 'Content-Type: application/json;charset=UTF-8' 
--data-binary '{"day":"tuesday","startAt":"07:00","finishAt":"08:30","module":5645015573331968,"branch":5681034041491456,"tutor":5711673465765888}' 
--compressed

###
GET http://127.0.0.1:3000/classes
?sort=-_updated
&max_results=5
&page=1
&embedded={"branch":true,"module":true,"tutor":true}
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOjU3MTIwODg5MzY3NDI5MTJ9.zq9a4uy732We7lClYCGSrAxDIRqnzY4j2SvW-RqF4gk

###
curl 'http://127.0.0.1:3000/students/dormant?sort=_deleted,name&max_results=9999' 
-H 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOjU3MTIwODg5MzY3NDI5MTJ9.zq9a4uy732We7lClYCGSrAxDIRqnzY4j2SvW-RqF4gk' 
--compressed

###
curl 'http://192.168.2.50:3000/schedules?embedded={"branch":true,"tutor":true,"module":true}&max_results=999' 
-H 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOjU3MTE2NzM0NjU3NjU4ODh9.JlKimThR7iQK6O0D7vVqeu3UK4LWUrYbSguGC-ir-Zs' 
--compressed