version:          '2'
services:
  web-main:
    build:        ./web-main
    volumes:
       - ./web-main:/project/app
    working_dir:  /project/app
    depends_on:
      - api-main
    command:      ["npm", "run", "build"]
  web-operation:
    build:        ./web-main
    volumes:
       - ./web-operation:/project/app
    working_dir:  /project/app
    depends_on:
      - api-main
    command:      ["npm", "run", "build"]
  # web-partner:
  #   build:      ./web-main
  #   volumes:
  #      - ./web-partner:/project/app
  #   working_dir: /project/app
  #   ports:
  #     - "83:8080"
  #   command:    ["npm", "run", "build"]
  api-main:
    build:        ./api-main
    volumes:
       - ./api-main:/project
    working_dir:  /project
    expose:
      - "3000"
    restart: unless-stopped
    environment:
      - JWT_KEY=${JWT_KEY}
    depends_on:
      - db-main
    command: bash -c "go build main.go && ./main"
    restart: unless-stopped
  db-main:
    build:        ./db-main
    expose:
      - "5432"
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - "80:80"
      - "81:81"
      - "82:82"
    depends_on:
      - web-main
      - web-operation
  pgadmin4:
    image:      fenglc/pgadmin4
    ports:
      - "5050:5050"
    links:
      - db-main:postgres
    environment:
      - DEFAULT_USER=${PGA_USER}
      - DEFAULT_PASSWORD=${PGA_PASS}
  # redis:
  #   image:      redis
