version:          '2'
services:
  api-main:
    build:        ./api-main
    volumes:
       - ./api-main:/project
    working_dir:  /project
    ports:
      - "90:1323"
    environment:
      - JWT_KEY=${JWT_KEY}
      - HOST=${HOST}
      - HOST_DB_API=${HOST_DB_API}
      - HOST_MQTT=${HOST_MQTT}
      - BIN_APP_PORT=1323
    depends_on:
      - db-api
    command: bash -c "go build main.go && ./main"
  db-api:
    image: postgrest/postgrest
#    remove ports on production
#    ports:
#      - "3000:3000"
    environment:
      - PGRST_DB_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - PGRST_DB_SCHEMA=public
      - PGRST_DB_ANON_ROLE=anon
      - PGRST_JWT_SECRET=${JWT_KEY}
    depends_on:
      - db
  db-admin:
    image:      adminer
    ports:
      - "99:8080"
    depends_on:
      - db
  db:
    build:        ./db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  nginx:
    image: nginx
    volumes:
      - ./web/tutor/dist:/usr/share/nginx/html/mtutor:ro
      - ./web/operation/dist:/usr/share/nginx/html/mops:ro
      - /etc/letsencrypt:/etc/letsencrypt
      - ./web/ssl.conf:/etc/nginx/ssl.conf
      - ./web/security.conf:/etc/nginx/security.conf
      - ./web/basic.conf:/etc/nginx/basic.conf
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - ./web/tmpl.nginx-mtutor.conf:/etc/nginx/conf.d/default.conf.tmpl
      - ./web/tmpl.nginx-mops.conf:/etc/nginx/conf.d/default-mops.conf.tmpl
      - ./web/nginx-log:/var/log/nginx
    environment:
      - NGINX_HOST_0=mtutor.id
      - NGINX_HOST_1=mops.id
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.conf.tmpl > /etc/nginx/conf.d/default.conf && envsubst < /etc/nginx/conf.d/default-mops.conf.tmpl > /etc/nginx/conf.d/default-mops.conf && nginx -g 'daemon off;'"
    ports:
      - "80:80"
      - "443:443"
