version:          '2'
services:
  api-main:
    build:        ./api-main
    volumes:
       - ./api-main:/project
    working_dir:  /project
    ports:
      - "90:1323"
    restart: unless-stopped
    environment:
      - JWT_KEY=${JWT_KEY}
      - DB_API=${DB_API}
    depends_on:
      - db-main
    links:
      - db-main
    command: bash -c "go build main-prod.go && ./main-prod"
    restart: unless-stopped
  mqtt:
    image: emqttd-docker-v2.3.7
    network_mode: "host"
    environment:
      - EMQ_HOST=${HOST}
      - EMQ_WAIT_TIME=21
  db-api:
    image: postgrest/postgrest
    depends_on:
      - db-main
    links:
      - db-main:db
    environment:
      - PGRST_DB_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-main:5432/${POSTGRES_DB}
      - PGRST_DB_SCHEMA=public
      - PGRST_DB_ANON_ROLE=anon
      - PGRST_JWT_SECRET=${JWT_KEY}
  db-main:
    build:        ./db-main
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  db-admin:
    image:      adminer
    ports:
      - "5050:8080"
    depends_on:
      - db-main
    links:
      - db-main:db
