version: '2'
services:
  api:
    build: ./api
    volumes:
      - ./api/app:/app
    ports:
      - "3000:3000"
    environment:
      - MONGO_JSON=${MONGO_JSON}
      - JWT_SECRET=${JWT_KEY}
      - JWT_ISSUER=codingcamp.id
      - DEBUG=1
      - HOST_MQTT=${HOST_MQTT}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    command: gunicorn --bind 0.0.0.0:3000 --timeout 90 --graceful-timeout 90 --reload main:app
  api-doc:
    image: swaggerapi/swagger-ui
    ports:
      - "3001:8080"
    environment:
      - API_URL=http://${HOST}:3000/api-docs
























