version:          '2'
services:
  web-main:
    build:
      context: ./web-main
      dockerfile: Dockerfile-build
    working_dir:  /usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - api-main
    links:
      - api-main
  api-main:
    build:        ./api-main
    volumes:
       - ./api-main:/project
    working_dir:  /project
    ports:
      - "82:1323"
    restart: unless-stopped
    environment:
      - JWT_KEY=${JWT_KEY}
    depends_on:
      - db-main
    links:
      - db-main
    command: bash -c "go build main.go && ./main"
    restart: unless-stopped
  db-main:
    build:        ./db-main
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  db-api:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    depends_on:
      - db-main
    links:
      - db-main:db
    environment:
      - PGRST_DB_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-main:5432/${POSTGRES_DB}
      - PGRST_DB_SCHEMA=public
      - PGRST_DB_ANON_ROLE=anon
      - PGRST_JWT_SECRET=${JWT_KEY}
  db-admin:
    image:      adminer
    ports:
      - "5050:8080"
    depends_on:
      - db-main
    links:
      - db-main:db
