version:          '2'
services:
  web-main:
    build:        ./web-main
    volumes:
       - ./web-main:/project/app
    working_dir:  /project/app
    ports:
      - "81:8080"
    depends_on:
      - api-main
    command:      ["npm", "run", "dev"]
  web-operation:
    build:        ./web-main
    volumes:
       - ./web-operation:/project/app
    working_dir:  /project/app
    ports:
      - "82:8080"
    depends_on:
      - api-main
    command:      ["npm", "run", "dev"]
  # web-partner:
  #   build:      ./web-main
  #   volumes:
  #      - ./web-partner:/project/app
  #   working_dir: /project/app
  #   ports:
  #     - "83:8080"
  #   command:    ["npm", "run", "dev"]
  api-main:
    build:        ./api-main
    volumes:
       - ./api-main:/project
    working_dir:  /project
    expose:
      - "3000"
    ports:
     - "84:3000"
    depends_on:
      - db-main
    command:      gin run
  db-main:
    build:        ./db-main
    expose:
      - "5432"
  # pgadmin4:
  #   image:      fenglc/pgadmin4
  #   ports:
  #     - "5050:5050"
  #   links:
  #     - db-main:postgres
  #   environment:
  #     - DEFAULT_USER=admin
  #     - DEFAULT_PASSWORD=xxx
  # redis:
  #   image:      redis
