version: '2'
services:
  # api:
  #   build: ./api
  #   volumes:
  #     - ./api/src:/app
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - SQLALCHEMY_DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
  #     - JWT_SECRET=${JWT_KEY}
  #     - JWT_ISSUER=codingcamp.id
  #     - DEBUG=1
  #     - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
  #     - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
  #     - HOST=${HOST}
  #     - HOST_IP=${HOST_IP}
  #     - HOST_STORAGE=${HOST_STORAGE}
  #     - HOST_MQTT=${HOST_MQTT}
  #     - MAIL_PASSWORD=${MAIL_PASSWORD}
  #   depends_on:
  #     - db
  #   command: gunicorn -b 0.0.0.0:3000 --reload main:app
  api-v2:
    build: ./api-v2
    volumes:
      - ./api-v2/src:/app
    ports:
      - "3000:3000"
    environment:
      - MONGO_JSON=${MONGO_JSON}
      - JWT_SECRET=${JWT_KEY}
      - JWT_ISSUER=codingcamp.id
      - DEBUG=1
      - HOST=${HOST}
      - HOST_IP=${HOST_IP}
      - HOST_STORAGE=${HOST_STORAGE}
      - HOST_MQTT=${HOST_MQTT}
    command: gunicorn --bind 0.0.0.0:3000 --timeout 90 --graceful-timeout 90 --reload main:app
  api-doc:
    image: swaggerapi/swagger-ui
    ports:
      - "3001:8080"
    environment:
      - API_URL=http://${HOST}:3000/api-docs
























