service: default
runtime: python37
api_version: 1

handlers:
- url: /.*
  script: auto

env_variables:
  MONGO_JSON: 'steep-eagle-7d9be40b59f4.json'
  JWT_SECRET: 'xhyk88xwaZh2R942Cs4D82PRjAdzJSSs'
  JWT_ISSUER: 'codingcamp.id'
  DEBUG: 0
  HOST_MQTT: 'iot.eclipse.org'
