# vars
@host = http://127.0.0.1:3000
@studentId = 5702167830724608
@username = xxx
@password = xxx

###
# @name sign
POST {{host}}/sign
Content-Type: application/json

{
    "username":"{{username}}",
    "password":"{{password}}",
    "role":["operation"]
} 

### 
# @name user
GET {{host}}/auth
Authorization: Bearer {{sign.response.body.$.token}}

###
POST http://127.0.0.1:3000/forgot_password
Content-Type: application/json;charset=UTF-8

{
    "username":"{{username}}",
    "role":["operation"]
}

###
GET http://127.0.0.1:3000/users
# ?max_results=5
# &page=1
# &show_deleted=true
# &sort=_deleted,-_updated
?where={"username":"fariz"}
# &where={"role":"tutor"}
Authorization: Bearer {{sign.response.body.$.token}}

###
GET {{host}}/users/{{user.response.body.$._id}}
Authorization: Bearer {{sign.response.body.$.token}}

###
# @name modules
GET {{host}}/modules
?where={"name":"/dumm/"}
Authorization: Bearer {{sign.response.body.$.token}}

###
# @name module
GET {{host}}/modules/{{modules.response.body.$._items.0._id}}
Authorization: Bearer {{sign.response.body.$.token}}

###
# @name branches
GET {{host}}/branches
Authorization: Bearer {{sign.response.body.$.token}}

###
# @name branch
GET {{host}}/branches/{{branches.response.body.$._items.0._id}}
Authorization: Bearer {{sign.response.body.$.token}}

###
# @name tutors
GET {{host}}/tutors
?sort=_deleted,-_updated
Authorization: Bearer {{sign.response.body.$.token}}
###
# @name tutor
GET {{host}}/tutors/{{tutors.response.body.$._items.0._id}}
Authorization: Bearer {{sign.response.body.$.token}}

###
POST {{host}}/classes
Authorization: Bearer {{sign.response.body.$.token}}
Content-Type: application/json

{
    "day":"tuesday","startAt":"07:00","finishAt":"08:30",
    "module":"{{module.response.body.$._id}}",
    "branch":"{{branch.response.body.$._id}}",
    "tutor":"{{tutor.response.body.$._id}}"
}


###
# @name classes
GET {{host}}/classes
?sort=-_updated
&max_results=5
&page=1
Authorization: Bearer {{sign.response.body.$.token}}

###
# @name class
GET {{host}}/classes/{{classes.response.body.$._items.0._id}}
Authorization: Bearer {{sign.response.body.$.token}}
###
GET {{host}}/classes/{{class.response.body.$._id}}/students
Authorization: Bearer {{sign.response.body.$.token}}

###
DELETE {{host}}/classes/{{class.response.body.$._id}}/students
Authorization: Bearer {{sign.response.body.$.token}}
###
POST {{host}}/classes/{{class.response.body.$._id}}/students
Authorization: Bearer {{sign.response.body.$.token}}
Content-Type: application/json

[
    {
        "class":"{{class.response.body.$._id}}",
        "student":"{{studentId}}"
    }
]
###
GET {{host}}/students/dormant?sort=_deleted,name&max_results=9999
Authorization: Bearer {{sign.response.body.$.token}}
###
GET {{host}}/students/
Authorization: Bearer {{sign.response.body.$.token}}

###
GET {{host}}/students/{{studentId}}
Authorization: Bearer {{sign.response.body.$.token}}
###
GET {{host}}/students/{{studentId}}/guardians
Authorization: Bearer {{sign.response.body.$.token}}
###
DELETE  {{host}}/students/{{studentId}}/guardians
Authorization: Bearer {{sign.response.body.$.token}}

###
POST {{host}}/students/{{studentId}}/guardians
Authorization: Bearer {{sign.response.body.$.token}}
Content-Type: application/json

[
    {
        "name":"guardian2",
        "email":"guardian2@ex.com",
        "contact":"guardian2 contact",
        "role":"guardian"
    }
]

###
GET http://127.0.0.1:3000/attendances_tutors
?sort=-_created
&max_results=5
&page=1
&embedded={"attendance":true,"attendance.class":true,"attendance.class.branch":true,"attendance.module":true,"tutor":true}
Authorization: Bearer {{sign.response.body.$.token}}

###
GET http://127.0.0.1:3000/attendances_students
?sort=-_created
&max_results=5
&page=1
&embedded={"student":true,"attendance":true,"attendance.class":true,"attendance.class.branch":true,"attendance.module":true,"tutor":true}
Authorization: Bearer {{sign.response.body.$.token}}