CREATE ROLE operation WITH LOGIN PASSWORD 'mysecretpassword';
CREATE ROLE tutor WITH LOGIN PASSWORD 'mysecretpassword';
CREATE ROLE student WITH LOGIN PASSWORD 'mysecretpassword';
CREATE ROLE parent WITH LOGIN PASSWORD 'mysecretpassword';
CREATE ROLE partner WITH LOGIN PASSWORD 'mysecretpassword';
REVOKE CONNECT ON DATABASE postgres
FROM
  PUBLIC;
GRANT CONNECT ON DATABASE postgres TO operation;
GRANT CONNECT ON DATABASE postgres TO tutor;
GRANT CONNECT ON DATABASE postgres TO student;
GRANT CONNECT ON DATABASE postgres TO parent;
GRANT CONNECT ON DATABASE postgres TO partner;
REVOKE ALL ON ALL TABLES IN SCHEMA public
FROM
  PUBLIC;
GRANT
SELECT
  ,
  INSERT,
UPDATE
  ,
  DELETE ON ALL TABLES IN SCHEMA public TO operation;
GRANT
SELECT
  ON ALL TABLES IN SCHEMA public TO tutor;
GRANT
SELECT
  ON ALL TABLES IN SCHEMA public TO student;
GRANT
SELECT
  ON ALL TABLES IN SCHEMA public TO parent;
GRANT
SELECT
  ON ALL TABLES IN SCHEMA public TO partner;
