-- truncate all table
--SELECT 'TRUNCATE ' || table_name || ' CASCADE;' FROM information_schema.tables WHERE table_schema='public' AND table_type='BASE TABLE';
--
--TRUNCATE sessions_students CASCADE;
--TRUNCATE sessions_tutors CASCADE;
--TRUNCATE sessions CASCADE;
--TRUNCATE class_students CASCADE;
--TRUNCATE classes CASCADE;
--TRUNCATE programs_modules CASCADE;
--TRUNCATE branches CASCADE;
--TRUNCATE users CASCADE;
--TRUNCATE programs CASCADE;
--TRUNCATE users_profile CASCADE;
--TRUNCATE modules CASCADE;
--TRUNCATE program_types CASCADE;

-- fixing sequence
--SELECT 'SELECT SETVAL(' ||
--       quote_literal(quote_ident(PGT.schemaname) || '.' || quote_ident(S.relname)) ||
--       ', COALESCE(MAX(' ||quote_ident(C.attname)|| '), 1) ) FROM ' ||
--       quote_ident(PGT.schemaname)|| '.'||quote_ident(T.relname)|| ';'
--FROM pg_class AS S,
--     pg_depend AS D,
--     pg_class AS T,
--     pg_attribute AS C,
--     pg_tables AS PGT
--WHERE S.relkind = 'S'
--    AND S.oid = D.objid
--    AND D.refobjid = T.oid
--    AND D.refobjid = C.attrelid
--    AND D.refobjsubid = C.attnum
--    AND T.relname = PGT.tablename
--ORDER BY S.relname;
--
--SELECT SETVAL('public.branches_id_seq', COALESCE(MAX(id), 1) ) FROM public.branches;
--SELECT SETVAL('public.classes_id_seq', COALESCE(MAX(id), 1) ) FROM public.classes;
--SELECT SETVAL('public.modules_id_seq', COALESCE(MAX(id), 1) ) FROM public.modules;
--SELECT SETVAL('public.program_types_id_seq', COALESCE(MAX(id), 1) ) FROM public.program_types;
--SELECT SETVAL('public.programs_id_seq', COALESCE(MAX(id), 1) ) FROM public.programs;
--SELECT SETVAL('public.programs_modules_id_seq', COALESCE(MAX(id), 1) ) FROM public.programs_modules;
--SELECT SETVAL('public.sessions_id_seq', COALESCE(MAX(id), 1) ) FROM public.sessions;
--SELECT SETVAL('public.users_id_seq', COALESCE(MAX(id), 1) ) FROM public.users;

-- set tutor_id
--WITH myconstants (tutor_id) as (
--   values (1)
--)

-- total kelas yang diaktifasi tutor_id=x
--select count(*) from (
--SELECT s_id,ts
--FROM _stats_tutors
--where s_tutor_id=tutor_id
--group by s_id,ts
--) a;

-- total durasi kelas yang diaktifasi tutor_id=x
--select sum(duration) from(
--SELECT finish_at_ts,start_at_ts,finish_at_ts-start_at_ts duration
--FROM _stats_tutors
--where s_tutor_id=tutor_id
--group by s_id,finish_at_ts,start_at_ts) a;

-- total review student dari kelas yang diaktifasi tutor_id=x
--select count(*) from (
--SELECT feedback
--FROM _stats_tutors
--where s_tutor_id=tutor_id and feedback is not null
--group by session_id,student_id,tutor_id,feedback
--) a;

-- rata2 semua rating yang diberikan pada kelas yang diaktifasi tutor_id=x
--select round(avg(avg),2) from(
--select (rating_interaction+rating_cognition+rating_creativity)/3.0 avg
--from _stats_tutors
--where s_tutor_id=tutor_id and student_id is not null
--) a;

--SELECT *
--FROM _stats_tutors
--where tutor_id=tutor_id
