# vars
# @host = https://api.steep-eagle.appspot.com
@host = http://127.0.0.1:3000
@username = op1
@password = 653caad8

###
# @name sign
POST {{host}}/sign
Content-Type: application/json

{
    "username":"{{username}}",
    "password":"{{password}}",
    "role":["operation"]
} 

@sign_token = {{sign.response.body.$.token}}

### 
# @name auth
GET {{host}}/auth
Authorization: Bearer {{sign_token}}


###
GET {{host}}/branches
Authorization: Bearer {{sign_token}}

###
# @name new_branch
POST {{host}}/branches
Authorization: Bearer {{sign_token}}
Content-Type: application/json

{
    "name":"branch1"
}

@branch_id = {{new_branch.response.body.$._id}}

###
# @name branch
GET {{host}}/branches/{{branch_id}}
Authorization: Bearer {{sign_token}}